steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install distutils
        run: |
          python -m pip install --upgrade pip
          pip install setuptools

      - name: Set PYTHON env var
        run: echo "PYTHON=$(which python)" >> $GITHUB_ENV

      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter=deemix-gui exec pnpm electron-rebuild

      # Added '--' to pass the arguments through turbo 
      - run: pnpm make -- --arch x64,arm64

      - name: Upload Artifacts
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            packages/gui/out/**/Deemix.exe
            packages/gui/out/**/Deemix*Setup.exe
            packages/gui/out/make/zip/**/*.zip
            packages/gui/out/make/deb/**/*.deb
